local Public= {
  withQuest = {
    Quest_1 = {
      Dialogs = {
        "First Phrase",
        "Second Phrase",
        "Third Phrase"
      },

      Options = {
        "First option",
        "Second option",
        "Third option"
      }
    }
  },

  withoutQuest = {
    OldForger = {
      Dialogs = {
        "First Phrase",
        "Second Phrase",
        "Third Phrase"
      }
    }
  }
}

return Public